allowBuilds:
  "@alicloud/openapi-core": true
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true

configDependencies:
  pacquet: ^0.11.12

enableGlobalVirtualStore: true

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - oxc-config-hope
  - oxfmt
  - oxlint
  - innenu-generator

trustPolicy: no-downgrade

trustPolicyExclude:
  # ali-oss, babel
  - semver@5.7.2 || 6.3.1
  # node types
  - undici-types@6.21.0
