title: 城乡居民基本医疗保险
tags:
  - 保险
icon: insurance
author: Mr.Hope
time: 2025-07-27T10:25:37.331Z
shareable: true
content:
  - tag: text
    type: info
    text:
      - 学校每年会统一组织全体学生办理“长春市城乡居民基本医疗保险”。

  - tag: title
    text: 简介

  - tag: p
    text: 城镇居民基本医疗保险是社会医疗保险的重要组成部分。它采取以政府为主导，个人（家庭）缴费为主、政府适度补助为辅的筹资方式，旨在为广大城镇居民提供可靠的医疗保障。

  - tag: text
    type: tip
    text:
      - 新生入学前在原籍缴纳的城乡居民基本医疗保险，其保障期通常持续到入学当年的12月31日，因此无需担心医保断缴问题。
      - 学校一般会在每年10月后，待原保险即将到期时，再统一组织新一年度的参保信息统计与缴费工作。

  - tag: text
    type: info
    header: 参保地与参保资格
    text:
      - 参保学生必须拥有教育部门正式登记的学籍。
      - 吉林省内的全日制在籍学生，统一在学籍所在地（即学校所在地）参保。
      - 若学生为吉林省内民政或乡村振兴部门认定的困难人员，可选择在身份认定地参保缴费，并享受当地的医保待遇政策；如选择在学籍地参保，则按普通学生身份享受相关待遇，参保资助及医疗救助等待遇需向身份认定地的医保部门申请。
      - 若学生为省外相关部门认定的困难人员，可选择在原籍参保并享受当地政策；如选择在学籍地（吉林省）参保，需全额缴纳个人保费，享受吉林省普通学生的医保待遇。

  - tag: title
    text: 信息录入

  - tag: p
    text:
      - 各班级辅导员会负责收集学生的参保信息。学校将通过医保局，统一将参保学生的保险经办机构变更为“长春市市本级社会医疗保险管理局”。

  - tag: title
    text: 缴费标准

  - tag: text
    type: info
    header: 2025年度缴费标准
    text:
      - 400 元/人/年

  - tag: title
    text: 缴费方式与时间

  - tag: text
    text:
      - 请密切关注辅导员的通知，在规定的集中缴费期内，通过“吉林税务社保缴费”小程序自行完成缴费。

  - tag: card
    action: miniProgram
    title: 城乡居民医保缴费
    appId: wx2bd3e1deb552a91c
    path: pages/index/index
    env:
      - wx

  - tag: img
    src: $img/insurance/base-pay.jpg
    env:
      - app
    watermark: true

  - tag: ul
    type: warning
    header: 缴费前确认
    text:
      - 确认自己的保险经办机构为“长春市市本级社会医疗保险管理局”。
      - 确认自己的缴费金额为 400 元。

  - tag: title
    text: 常见问题

  - tag: ul
    type: info
    header: 缴费时发现经办机构不是长春市？
    text:
      - 若已在原籍缴费，则享受原籍的医保政策。如希望享受长春市的大学生医保待遇，需先联系原籍医保部门办理停保退费，再联系辅导员录入新参保信息，待小程序中的信息（金额、经办机构）均正确无误后再缴费。
      - 若未在任何地方缴费，请联系辅导员在参保平台进行“学生参保身份变更”操作，待小程序信息更新正确后，即可缴费。

  - tag: text
    type: info
    header: 缴费时显示的金额与应缴金额不符怎么办？
    text:
      - 如果小程序显示的金额与您的应缴金额（例如，您属于困难学生，但显示为普通学生缴费标准）不符，请按以下步骤处理：
      - 首先，立即联系辅导员，确认学校上报的参保身份是否正确。
      - 若身份信息无误，可能需要由学生本人或家长携带户口本、困难身份证明（如低保证）及身份证件，前往长春市繁荣路医保局服务大厅进行身份标识认定。外地（县）学生可联系当地医保局咨询办理方式。

  - tag: title
    text: 保险生效时间

  - tag: ul
    header: 2025年度城乡居民基本医疗保险
    text:
      - 在集中预缴期内完成缴费的，医保待遇期为2025年1月1日至2025年12月31日。
      - 若错过集中缴费期进行补缴，将有3个月的待遇等待期（即等待期内无法享受医保报销）。

  - tag: title
    text: 保险报销

  - tag: text
    type: info
    header: 请参见长春市城乡居民基本医疗保险报销
    path: reimburse
