title: 运动训练
tags:
  - 体育学院
  - 专业介绍
desc: |-
  来源: 2025 年本科招生指南
time: 2025-06-22T18:36:07.304Z
cite:
  - https://book.zjzw.cn/books/lzsj/mobile/index.html
shareable: true
content:
  - tag: title
    text: 专业简介

  - tag: p
    text: 为普通类专业，旨在培养适应国家体育发展战略要求，具备致力于体育强国和健康中国2030规划纲要建设需要，具有高度的社会责任担当，坚定的体育学科自信；具备从事训练竞赛、全民健身学科素养；掌握训练与健身理论与方法，具有精湛的运动技能、扎实的教学与训练技能；拥有可持续发展的人文知识底蕴和潜能，赋予创新精神和实践智慧，胜任学校竞技体育训练、社会体育指导和体育教学等方面工作的复合型专门人才。

  - tag: title
    text: 主干课程

  - tag: ul
    text:
      - 运动解剖学
      - 运动生理学
      - 体育心理学
      - 运动生物力学
      - 体育学概论
      - 太极与养生
      - 体育科学研究方法
      - 体育保健学
      - 运动生物化学
      - 运动训练学
      - 田径
      - 体操
      - 篮球
      - 排球
      - 足球
      - 武术
      - 游泳
      - 速度滑冰
      - 滑雪
      - 专项训练与理论

  - tag: title
    text: 学费价格

  - tag: text
    text: 9000 元/年

  - tag: title
    text: 就业方向

  - tag: text
    text: 大、中学体育教师，各级各类体育运动学校教练员，各级体育职能部门管理人员，社会体育指导员及体育俱乐部管理人员。
