name: Generate and deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "config/scraper.json"
      - "data/**"
      - "pages/**"
      - "scripts/**"
      - "site/**"
      - "package.json"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm ci

      - name: Generate Site
        run: pnpm run site:generate

      - name: Build Site
        run: pnpm run site:build

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: .site/.vuepress/dist
          single-commit: true

      - name: Trigger Hook
        run: curl -s "${{ secrets.BT_DOCS_WEBHOOK_URL }}"

      - name: Wait 30 seconds for the deploy to finish
        run: sleep 30

  scrape:
    needs: deploy
    uses: ./.github/workflows/scraper.yml
    secrets:
      MEILISEARCH_MASTER_KEY: ${{ secrets.MEILISEARCH_MASTER_KEY }}
