name: Deploy resource

on:
  push:
    branches:
      - main
    paths:
      - "config/**"
      - "data/**"
      - "file/**"
      - "img/**"
      - "pages/**"
      - "service/**"
      - "scripts/**"
      - "package.json"

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm ci

      - name: Write env files
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Generate resource
        run: |
          pnpm run resource:generate

      - name: Sync OSS
        run: |
          pnpm run sync:oss

      - name: Deploy to resource branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: resource
          folder: .resource
          single-commit: true

      - name: Trigger Hook
        run: curl -s "${{ secrets.BT_RESOURCE_WEBHOOK_URL }}"
