name: Deploy resource

on:
  push:
    branches:
      - main
    paths:
      - "config/**"
      - "data/**"
      - "file/**"
      - "img/**"
      - "pages/**"
      - "service/**"
      - "scripts/**"
      - "package.json"

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Write env files
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Generate resource
        run: |
          pnpm run resource:generate

      - name: Sync OSS
        run: |
          pnpm run sync:oss

      - name: Deploy to resource branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: resource
          folder: .resource
          single-commit: true

  deploy-server:
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: resource
          fetch-depth: 0

      - name: Config environment
        env:
          HOST: direct.innenu.com
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Host $HOST" >> ~/.ssh/config
          echo "  HostName $HOST" >> ~/.ssh/config
          echo "  Port $SSH_PORT" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          git config --global user.name 'Mr.Hope'
          git config --global user.email 'mister-hope@outlook.com'

      - name: Deploy
        env:
          HOST: direct.innenu.com
          DEST: /www/wwwroot/innenu-res
          BRANCH: resource
        run: |
          git push -f git@$HOST:$DEST $BRANCH
          ssh git@$HOST "cd $DEST && git reset --hard HEAD"
